name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release] # Adding just in case I need Debug

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' # Pithon haha get it?

      - name: Install Conan
        run: |
          pip install conan
          conan --version

      - name: Cache Conan Packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ matrix.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ matrix.os }}-conan-

      - name: Detect Conan Profile
        run: |
          conan profile detect --force

      - name: Conan Install Dependencies
        run: |
          conan install . -s build_type=${{ matrix.build_type }} --build=missing -pr:b=default -pr:h=default

      - name: CMake Configure
        run: |
          cmake -S . -B build/${{ matrix.build_type }} --preset conan-${{ matrix.build_type == 'Debug' && 'debug' || 'release' }}

      - name: CMake Build
        run: |
          cmake --build build/${{ matrix.build_type }} -j